import asyncio
import json
import logging
import re
import shutil
import time
from pathlib import Path
from typing import Optional

logger = logging.getLogger("inframatik.services")

SERVICES_FILE = Path.home() / ".config" / "inframatik" / "services.json"
PORTS_ENV_FILE = Path.home() / ".config" / "inframatik" / "ports.env"
UNIT_DIR = Path.home() / ".config" / "systemd" / "user"
PORT_RANGE = range(8000, 9000)
UNIT_PREFIX = "infra-"
_SYSTEMCTL_IS_ACTIVE = ("is-active",)
_SYSTEMCTL_ENABLE_NOW = ("enable", "--now")
_SYSTEMCTL_DISABLE_NOW = ("disable", "--now")
_SYSTEMCTL_RESTART = ("restart",)

UNIT_TEMPLATE = """\
[Unit]
Description=infra: {name}
After=network-online.target

[Service]
Type=simple
WorkingDirectory={working_dir}
ExecStart={command}
Restart=on-failure
RestartSec=5s
Environment=PORT={port}
Environment=HOST={host}

[Install]
WantedBy=default.target
"""


def _load_registry() -> dict:
    if SERVICES_FILE.exists():
        try:
            data = json.loads(SERVICES_FILE.read_text())
            if not isinstance(data, dict):
                raise ValueError("Service registry root must be a JSON object")
            return data
        except (json.JSONDecodeError, ValueError, OSError) as e:
            logger.error("Service registry is invalid (%s): %s", SERVICES_FILE, e)
            _quarantine_corrupt_registry(SERVICES_FILE)
            recovered = _load_registry_backup()
            if recovered is not None:
                logger.warning(
                    "Recovered service registry from backup (%s) after corruption",
                    _registry_backup_file(),
                )
                _save_registry(recovered)
                return recovered
            return {}
    return {}


def _save_registry(data: dict):
    SERVICES_FILE.parent.mkdir(parents=True, exist_ok=True)
    _backup_registry()
    SERVICES_FILE.write_text(json.dumps(data, indent=2))
    _write_ports_env(data)


def _registry_backup_file() -> Path:
    return Path(f"{SERVICES_FILE}.bak")


def _backup_registry():
    if not SERVICES_FILE.exists():
        return
    backup = _registry_backup_file()
    try:
        backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(SERVICES_FILE, backup)
    except OSError as e:
        logger.warning("Failed to write registry backup (%s): %s", backup, e)


def _load_registry_backup() -> Optional[dict]:
    backup = _registry_backup_file()
    if not backup.exists():
        logger.warning("No service registry backup found at %s", backup)
        return None
    try:
        data = json.loads(backup.read_text())
        if not isinstance(data, dict):
            raise ValueError("Backup registry root must be a JSON object")
        return data
    except (json.JSONDecodeError, ValueError, OSError) as e:
        logger.error("Service registry backup is invalid (%s): %s", backup, e)
        return None


def _quarantine_corrupt_registry(path: Path):
    suffix = f".corrupt-{time.time_ns()}"
    quarantine = Path(f"{path}{suffix}")
    try:
        path.replace(quarantine)
        logger.warning("Moved corrupt service registry to %s", quarantine)
    except OSError as e:
        logger.error("Failed to quarantine corrupt service registry (%s): %s", path, e)


def _env_var_name(name: str) -> str:
    return f"INFRA_{name.replace('-', '_').upper()}_PORT"


def _write_ports_env(registry: dict):
    lines = [f"# Auto-generated by inframatik — do not edit"]
    for name, svc in sorted(registry.items()):
        lines.append(f"export {_env_var_name(name)}={svc['port']}")
    PORTS_ENV_FILE.write_text("\n".join(lines) + "\n")


def _unit_name(name: str) -> str:
    return f"{UNIT_PREFIX}{name}.service"


def _unit_path(name: str) -> Path:
    return UNIT_DIR / _unit_name(name)


async def _run(cmd: list[str]) -> tuple[int, str]:
    proc = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT
    )
    stdout, _ = await proc.communicate()
    return proc.returncode, stdout.decode().strip()


async def _systemctl(action_tokens: tuple[str, ...], unit: str) -> tuple[int, str]:
    if not action_tokens:
        raise ValueError("systemctl action cannot be empty")
    for token in action_tokens:
        if not token or any(ch.isspace() for ch in token):
            raise ValueError("systemctl action tokens must be explicit argv parts")
    return await _run(["systemctl", "--user", *action_tokens, unit])


async def _daemon_reload():
    await _run(["systemctl", "--user", "daemon-reload"])


def _validate_name(name: str):
    if not re.match(r"^[a-z0-9][a-z0-9_-]*$", name):
        raise ValueError("Name must be lowercase alphanumeric, hyphens, underscores")
    if len(name) > 48:
        raise ValueError("Name must be 48 characters or less")


def _validate_command(command: str):
    if not command:
        raise ValueError("Command must be a single line")
    if any(ord(ch) < 32 for ch in command):
        raise ValueError("Command contains unsupported control characters")
    if ";" in command:
        raise ValueError("Command cannot contain semicolons")


def _validate_working_dir(working_dir: str):
    if any(ord(ch) < 32 for ch in working_dir):
        raise ValueError("Working directory contains unsupported control characters")


def get_allocated_ports() -> set[int]:
    registry = _load_registry()
    return {svc["port"] for svc in registry.values()}


def next_available_port() -> Optional[int]:
    used = get_allocated_ports()
    for port in PORT_RANGE:
        if port not in used:
            return port
    return None


async def get_service_status(name: str) -> str:
    code, output = await _systemctl(_SYSTEMCTL_IS_ACTIVE, _unit_name(name))
    return output  # "active", "inactive", "failed", etc.


async def list_services() -> list[dict]:
    registry = _load_registry()
    services = []
    for name, svc in registry.items():
        status = await get_service_status(name)
        services.append({**svc, "name": name, "status": status})
    return services


async def register_service(
    name: str,
    command: str,
    working_dir: str,
    hostname: Optional[str] = None,
    lan: bool = False,
) -> dict:
    _validate_name(name)
    _validate_command(command)
    _validate_working_dir(working_dir)

    registry = _load_registry()

    if name in registry:
        raise ValueError(f"Service '{name}' already exists")

    port = next_available_port()
    if port is None:
        raise ValueError("No ports available in range 8000-8999")

    working_path = Path(working_dir).expanduser().resolve()
    if not working_path.is_dir():
        raise ValueError(f"Working directory does not exist: {working_dir}")

    host = "0.0.0.0" if lan else "127.0.0.1"
    # Escape % as %% for systemd (prevents specifier expansion)
    safe_command = command.replace("%", "%%")
    unit_content = UNIT_TEMPLATE.format(
        name=name,
        working_dir=str(working_path),
        command=safe_command,
        port=port,
        host=host,
    )
    # Reserve the port immediately (before any async operations)
    svc = {
        "port": port,
        "command": command,
        "working_dir": str(working_path),
        "hostname": hostname,
        "lan": lan,
    }
    registry[name] = svc
    _save_registry(registry)

    _unit_path(name).write_text(unit_content)
    await _daemon_reload()

    # Add CF tunnel route + DNS + Access app if hostname provided
    cf_route_added = False
    if hostname:
        try:
            from tunnel import add_tunnel_route, create_dns_record, create_access_app, _load_cf_config
            await add_tunnel_route(hostname, port)
            await create_dns_record(hostname)
            cf_cfg = _load_cf_config()
            policy_id = cf_cfg.get("default_policy_id") if cf_cfg else None
            if policy_id:
                await create_access_app(name, hostname, policy_id)
            cf_route_added = True
        except Exception as e:
            logger.debug("CF setup skipped for %s: %s", name, e)

    return {**svc, "name": name, "status": "inactive", "unit": _unit_name(name), "cf_route_added": cf_route_added}


async def deregister_service(name: str):
    registry = _load_registry()
    if name not in registry:
        raise ValueError(f"Service '{name}' not found")

    await _systemctl(_SYSTEMCTL_DISABLE_NOW, _unit_name(name))

    unit = _unit_path(name)
    if unit.exists():
        unit.unlink()
    await _daemon_reload()

    svc = registry.pop(name)

    # Remove CF tunnel route + DNS + Access app if hostname was set
    if svc.get("hostname"):
        try:
            from tunnel import remove_tunnel_route, delete_dns_record, delete_access_app
            await remove_tunnel_route(svc["hostname"])
            await delete_dns_record(svc["hostname"])
            await delete_access_app(svc["hostname"])
        except Exception as e:
            logger.debug("CF cleanup skipped for %s: %s", name, e)

    _save_registry(registry)
    return svc


async def start_service(name: str) -> str:
    registry = _load_registry()
    if name not in registry:
        raise ValueError(f"Service '{name}' not found")
    code, output = await _systemctl(_SYSTEMCTL_ENABLE_NOW, _unit_name(name))
    if code != 0:
        raise RuntimeError(f"Failed to start: {output}")
    return await get_service_status(name)


async def stop_service(name: str) -> str:
    registry = _load_registry()
    if name not in registry:
        raise ValueError(f"Service '{name}' not found")
    code, output = await _systemctl(_SYSTEMCTL_DISABLE_NOW, _unit_name(name))
    if code != 0:
        raise RuntimeError(f"Failed to stop: {output}")
    return await get_service_status(name)


async def restart_service(name: str) -> str:
    registry = _load_registry()
    if name not in registry:
        raise ValueError(f"Service '{name}' not found")
    code, output = await _systemctl(_SYSTEMCTL_RESTART, _unit_name(name))
    if code != 0:
        raise RuntimeError(f"Failed to restart: {output}")
    return await get_service_status(name)


async def get_service_logs(name: str, lines: int = 100) -> str:
    registry = _load_registry()
    if name not in registry:
        raise ValueError(f"Service '{name}' not found")
    _, output = await _run(
        ["journalctl", "--user", "-u", _unit_name(name), "-n", str(lines), "--no-pager"]
    )
    return output
